services:
  - type: web
    name: papersetu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn conference_mgmt.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: conference_mgmt.settings 